cache:
  mount:
    - /drone/bundle

compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test

branch:
  - master
  - develop

build:
  image: "ruby:2.2.5"
  commands:
    - cp config/drone.database.yml config/database.yml
    - bundle install --path /drone/bundle
    - bundle exec rake db:schema:load
    - bundle exec rake test:all
  environment:
    - RAILS_ENV=test

# services:
#   - postgres

deploy:
  heroku:
    app: rails-sampleapp-kilik
    token: $$HEROKU_TOKEN
    when:
      branch: master

notify:
  email:
    from: romain@endelin.fr
    host: endelin.fr
    port: 465
    username: kilik
    password: "$$EMAIL_PASSWORD"
    recipients:
      - romain@endelin.fr
